### ISSUE TITLE
Latency problems when upgrading to 3.3.0 from 3.1.7 

### ISSUE THREAD

**Issue by fizzy123** [leolabs/ableton-js#101] opened 2023-07-24 19:52 UTC
Hi! I've just updated to the 3.3.0 version of this library from 3.1.7 and am noticing some significant differences in latency.

Here is the code I'm using to test the latency:
```
const { Ableton } = require("ableton-js");
const ableton = new Ableton({ logger: console });

(async () => {
  let start = (new Date()).getTime()
  await ableton.start();
  let time = await ableton.song.get("current_song_time");
  console.log(time)
  console.log("all set")
  console.log(((new Date()).getTime() - start))
})()
```
I'm running this code on a fresh new Ableton project. When I do so on 3.1.7, the script takes ~35ms.  However, on 3.3.0, the script takes ~300ms.

I am downgrading for now and can help with any debugging. Thanks for your continued development on this great project!

**Comment by leolabs** [comment] 2023-07-24 21:35
This might have been caused by my attempts to fix flaky behavior in Live 11.3. With 3.3.0 installed, could you edit the Config.py file and set `FAST_POLLING` to `True`, then restart Live and run your script again to see if that makes a difference?

**Comment by fizzy123** [comment] 2023-07-25 05:25
Very slightly different - ~40ms on 3.1.7 and ~50ms on 3.3.0 with `FAST_POLLING` set to true.

**Comment by leolabs** [comment] 2023-07-25 12:01
Nice, that's a step in the right direction! I'll see if I can improve this further without freezing Live's UI. Which version of Live are you using ableton-js with?

**Comment by fizzy123** [comment] 2023-07-25 18:57
I'm using Ableton version `11.3.4`, which i think this is the latest version.

FYI, for me, the difference is small enough that it doesn't affect my workflow. Please feel free to close if that minor timing difference is the only thing keeping the issue open!

**Comment by leolabs** [comment] 2023-07-25 21:12
Alright, thank you for letting me know! I'll close the issue then :)

**Closed by leolabs** 2023-07-25 21:12 UTC
